# Generated by Django 3.0.3 on 2020-11-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artproject_project_researchproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
