[package]
name = "with_python"
version = "0.1.0"
authors = ["seongpil0948 <seongpil0948@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# PyO3 is a fork of rust-cpython, more advanced, but it only works on the nightly Rust

# [“cdylib”] :tells the compiler that our module will be a dynamic library:
# a .dll file on Windows, .so on Linux, or .dylib on Mac.
[lib]
name = "with_python"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
